<?php

namespace AutomaticWordpress;

use Exception;

class Lang
{
    const AF = 'af';
    const AK = 'ak';
    const SQ = 'sq';
    const AM = 'am';
    const AR = 'ar';
    const HY = 'hy';
    const RUP = 'rup';
    const AS = 'as';
    const AZ = 'az';
    const AZ_TR = 'az-tr';
    const BA = 'ba';
    const EU = 'eu';
    const BEL = 'bel';
    const BN = 'bn';
    const BS = 'bs';
    const BG = 'bg';
    const MYA = 'mya';
    const CA = 'ca';
    const BAL = 'bal';
    const ZH_CN = 'zh-cn';
    const ZH_HK = 'zh-hk';
    const ZH_TW = 'zh-tw';
    const CO = 'co';
    const HR = 'hr';
    const CS = 'cs';
    const DA = 'da';
    const DV = 'dv';
    const NL = 'nl';
    const NL_BE = 'nl-be';
    const EN = '';
    const EN_AU = 'en-au';
    const EN_CA = 'en-ca';
    const EN_GB = 'en-gb';
    const EO = 'eo';
    const ET = 'et';
    const FO = 'fo';
    const FI = 'fi';
    const FR_BE = 'fr-be';
    const FR = 'fr';
    const FY = 'fy';
    const FUC = 'fuc';
    const GL = 'gl';
    const KA = 'ka';
    const DE = 'de';
    const DE_CH = 'de-ch';
    const EL = 'el';
    const GN = 'gn';
    const GU = 'gu';
    const HAW = 'haw';
    const HAZ = 'haz';
    const HE = 'he';
    const HI = 'hi';
    const HU = 'hu';
    const IS = 'is';
    const IDO = 'ido';
    const ID = 'id';
    const GA = 'ga';
    const IT = 'it';
    const JA = 'ja';
    const JV = 'jv';
    const KN = 'kn';
    const KK = 'kk';
    const KM = 'km';
    const KIN = 'kin';
    const KY = 'ky';
    const KO = 'ko';
    const CKB = 'ckb';
    const LO = 'lo';
    const LV = 'lv';
    const LI = 'li';
    const LIN = 'lin';
    const LT = 'lt';
    const LB = 'lb';
    const MK = 'mk';
    const MG = 'mg';
    const MS = 'ms';
    const ML = 'ml';
    const MR = 'mr';
    const XMF = 'xmf';
    const MN = 'mn';
    const ME = 'me';
    const NE = 'ne';
    const NB = 'nb';
    const NN = 'nn';
    const ORY = 'ory';
    const OS = 'os';
    const PS = 'ps';
    const FA = 'fa';
    const FA_AF = 'fa-af';
    const PL = 'pl';
    const PT_BR = 'pt-br';
    const PT = 'pt';
    const PA = 'pa';
    const RHG = 'rhg';
    const RO = 'ro';
    const RU = 'ru';
    const RU_UA = 'ru-ua';
    const RUE = 'rue';
    const SAH = 'sah';
    const SA_IN = 'sa-in';
    const SRD = 'srd';
    const GD = 'gd';
    const SR = 'sr';
    const SD = 'sd';
    const SI = 'si';
    const SK = 'sk';
    const SL = 'sl';
    const SO = 'so';
    const AZB = 'azb';
    const ES_AR = 'es-ar';
    const ES_CL = 'es-cl';
    const ES_CO = 'es-co';
    const ES_MX = 'es-mx';
    const ES_PE = 'es-pe';
    const ES_PR = 'es-pr';
    const ES = 'es';
    const ES_VE = 'es-ve';
    const SU = 'su';
    const SW = 'sw';
    const SV = 'sv';
    const GSW = 'gsw';
    const TL = 'tl';
    const TG = 'tg';
    const TZM = 'tzm';
    const TA = 'ta';
    const TA_LK = 'ta-lk';
    const TT = 'tt';
    const TE = 'te';
    const TH = 'th';
    const BO = 'bo';
    const TIR = 'tir';
    const TR = 'tr';
    const TUK = 'tuk';
    const UG = 'ug';
    const UK = 'uk';
    const UR = 'ur';
    const UZ = 'uz';
    const VI = 'vi';
    const WA = 'wa';
    const CY = 'cy';
    const YOR = 'yor';

    public static $langCodes = [
        Lang::AF => 'af',
        Lang::AK => 'ak',
        Lang::SQ => 'sq',
        Lang::AM => 'am',
        Lang::AR => 'ar',
        Lang::HY => 'hy',
        Lang::RUP => 'rup_MK',
        Lang::AS => 'as',
        Lang::AZ => 'az',
        Lang::AZ_TR => 'az_TR',
        Lang::BA => 'ba',
        Lang::EU => 'eu',
        Lang::BEL => 'bel',
        Lang::BN => 'bn_BD',
        Lang::BS => 'bs_BA',
        Lang::BG => 'bg_BG',
        Lang::MYA => 'my_MM',
        Lang::CA => 'ca',
        Lang::BAL => 'bal',
        Lang::ZH_CN => 'zh_CN',
        Lang::ZH_HK => 'zh_HK',
        Lang::ZH_TW => 'zh_TW',
        Lang::CO => 'co',
        Lang::HR => 'hr',
        Lang::CS => 'cs_CZ',
        Lang::DA => 'da_DK',
        Lang::DV => 'dv',
        Lang::NL => 'nl_NL',
        Lang::NL_BE => 'nl_BE',
        Lang::EN => '',
        Lang::EN_AU => 'en_AU',
        Lang::EN_CA => 'en_CA',
        Lang::EN_GB => 'en_GB',
        Lang::EO => 'eo',
        Lang::ET => 'et',
        Lang::FO => 'fo',
        Lang::FI => 'fi',
        Lang::FR_BE => 'fr_BE',
        Lang::FR => 'fr_FR',
        Lang::FY => 'fy',
        Lang::FUC => 'fuc',
        Lang::GL => 'gl_ES',
        Lang::KA => 'ka_GE',
        Lang::DE => 'de_DE',
        Lang::DE_CH => 'de_CH',
        Lang::EL => 'el',
        Lang::GN => 'gn',
        Lang::GU => 'gu_IN',
        Lang::HAW => 'haw_US',
        Lang::HAZ => 'haz',
        Lang::HE => 'he_IL',
        Lang::HI => 'hi_IN',
        Lang::HU => 'hu_HU',
        Lang::IS => 'is_IS',
        Lang::IDO => 'ido',
        Lang::ID => 'id_ID',
        Lang::GA => 'ga',
        Lang::IT => 'it_IT',
        Lang::JA => 'ja',
        Lang::JV => 'jv_ID',
        Lang::KN => 'kn',
        Lang::KK => 'kk',
        Lang::KM => 'km',
        Lang::KIN => 'kin',
        Lang::KY => 'ky_KY',
        Lang::KO => 'ko_KR',
        Lang::CKB => 'ckb',
        Lang::LO => 'lo',
        Lang::LV => 'lv',
        Lang::LI => 'li',
        Lang::LIN => 'lin',
        Lang::LT => 'lt_LT',
        Lang::LB => 'lb_LU',
        Lang::MK => 'mk_MK',
        Lang::MG => 'mg_MG',
        Lang::MS => 'ms_MY',
        Lang::ML => 'ml_IN',
        Lang::MR => 'mr',
        Lang::XMF => 'xmf',
        Lang::MN => 'mn',
        Lang::ME => 'me_ME',
        Lang::NE => 'ne_NP',
        Lang::NB => 'nb_NO',
        Lang::NN => 'nn_NO',
        Lang::ORY => 'ory',
        Lang::OS => 'os',
        Lang::PS => 'ps',
        Lang::FA => 'fa_IR',
        Lang::FA_AF => 'fa_AF',
        Lang::PL => 'pl_PL',
        Lang::PT_BR => 'pt_BR',
        Lang::PT => 'pt_PT',
        Lang::PA => 'pa_IN',
        Lang::RHG => 'rhg',
        Lang::RO => 'ro_RO',
        Lang::RU => 'ru_RU',
        Lang::RU_UA => 'ru_UA',
        Lang::RUE => 'rue',
        Lang::SAH => 'sah',
        Lang::SA_IN => 'sa_IN',
        Lang::SRD => 'srd',
        Lang::GD => 'gd',
        Lang::SR => 'sr_RS',
        Lang::SD => 'sd_PK',
        Lang::SI => 'si_LK',
        Lang::SK => 'sk_SK',
        Lang::SL => 'sl_SI',
        Lang::SO => 'so_SO',
        Lang::AZB => 'azb',
        Lang::ES_AR => 'es_AR',
        Lang::ES_CL => 'es_CL',
        Lang::ES_CO => 'es_CO',
        Lang::ES_MX => 'es_MX',
        Lang::ES_PE => 'es_PE',
        Lang::ES_PR => 'es_PR',
        Lang::ES => 'es_ES',
        Lang::ES_VE => 'es_VE',
        Lang::SU => 'su_ID',
        Lang::SW => 'sw',
        Lang::SV => 'sv_SE',
        Lang::GSW => 'gsw',
        Lang::TL => 'tl',
        Lang::TG => 'tg',
        Lang::TZM => 'tzm',
        Lang::TA => 'ta_IN',
        Lang::TA_LK => 'ta_LK',
        Lang::TT => 'tt_RU',
        Lang::TE => 'te',
        Lang::TH => 'th',
        Lang::BO => 'bo',
        Lang::TIR => 'tir',
        Lang::TR => 'tr_TR',
        Lang::TUK => 'tuk',
        Lang::UG => 'ug_CN',
        Lang::UK => 'uk',
        Lang::UR => 'ur',
        Lang::UZ => 'uz_UZ',
        Lang::VI => 'vi',
        Lang::WA => 'wa',
        Lang::CY => 'cy',
        Lang::YOR => 'yor'
    ];

    public static function getCode(string $lang) : string
    {
        return self::$langCodes[$lang] ?? Lang::EN;
    }

    public static function resolveLang($lang) : string
    {
        $lang = strtolower($lang);
        if (is_null($lang) || !in_array($lang, array_keys(self::$langCodes))) {
            return Lang::EN;
        }else {
            return $lang;
        }
    }
}